### ISSUE TITLE
请问，训练需要至少多大的显存？

### ISSUE THREAD

**Issue by LiuChaoXD** [HIT-SCIR/Chinese-Mixtral-8x7B#1]
你好，请问在训练过程中，使用了多少gpu？以及至少需要多大的显存才可以训练？

**Comment by jubgjf** [comment]
使用24 * A800
如果使用zero stage-1，per_device_train_batch_size=16，以及[`script/train.sh`](https://github.com/HIT-SCIR/Chinese-Mixtral-8x7B/blob/37b94de8b6e0a869864b2c31a0ace42d1002da04/scripts/train.sh#L30)里的LoRA设置，单卡显存占用大约是60GB。

**Comment by LiuChaoXD** [comment]
> 使用24 * A800 如果使用zero stage-1，per_device_train_batch_size=16，以及[`script/train.sh`](https://github.com/HIT-SCIR/Chinese-Mixtral-8x7B/blob/37b94de8b6e0a869864b2c31a0ace42d1002da04/scripts/train.sh#L30)里的LoRA设置，单卡显存占用大约是60GB。

多谢，看来我是训练不了了～～～～
