### ISSUE TITLE
代码中缺失了调用init_embeddings.py的脚本，纯新手，能提供一下吗？

### ISSUE THREAD

**Issue by whosyourdadds** [HIT-SCIR/Chinese-Mixtral-8x7B#10]

**Comment by jubgjf** [comment]
您好，可以参考对这部分[参数](https://github.com/HIT-SCIR/Chinese-Mixtral-8x7B/blob/37b94de8b6e0a869864b2c31a0ace42d1002da04/models/init_embeddings.py#L54C1-L60C3)的说明：
```python
def main(
        old_tokenizer: str,          # 原版模型tokenizer加载路径
        new_tokenizer: str,          # 扩词表模型tokenizer加载路径
        old_model: str,              # 原版模型加载路径，该目录下的权重文件需要是一个单独的`pytorch_model.bin`
        new_model: str,              # 扩词表模型保存路径
        save_embedding_plots: bool,  # 是否绘制embedding
):
```

调用方式为：
```shell
$ python models/init_embeddings.py --old_tokenizer /path/to/mixtral --new_tokenizer /path/to/chinese-mixtral --old_model /path/to/mixtral --new_model /path/to/chinese-mixtral --save_embedding_plots
```

**Comment by whosyourdadds** [comment]
> 您好，可以参考这部分[参数](https://github.com/HIT-SCIR/Chinese-Mixtral-8x7B/blob/37b94de8b6e0a869864b2c31a0ace42d1002da04/models/init_embeddings.py#L54C1-L60C3)的说明：
> 
> ```python
> def main(
>         old_tokenizer: str,          # 原版模型tokenizer加载路径
>         new_tokenizer: str,          # 扩词表模型tokenizer加载路径
>         old_model: str,              # 原版模型加载路径，该目录下的权重文件需要是一个单独的`pytorch_model.bin`
>         new_model: str,              # 扩词表模型保存路径
>         save_embedding_plots: bool,  # 是否绘制embedding
> ):
> ```
> 
> 调用方式为：
> 
> ```shell
> $ python models/init_embeddings.py --old_tokenizer /path/to/mixtral --new_tokenizer /path/to/chinese-mixtral --old_model /path/to/mixtral --new_model /path/to/chinese-mixtral --save_embedding_plots
> ```

好的，多谢
