### ISSUE TITLE
请教一下预训练数据使用情况

### ISSUE THREAD

**Issue by CLeafYeah** [HIT-SCIR/Chinese-Mixtral-8x7B#13]
中文数据集与英文数据集均预训练了2epoch还是仅英文训练了2epoch呢？  感谢回复

**Comment by jubgjf** [comment]
英文是2 epoch，中文是1 epoch

我们用的英文数据集只有大概6B token，比较少，所以重复了两次
中文数据大概有150B token，我们只采样了一部分进行训练

**Comment by CLeafYeah** [comment]
感谢回复，我们这边借鉴贵项目的思路做了一个词表扩充的预训练，用的glm 1.5B，用了22年全部的数据，中文，发现验证集ppl 一直比较高，想请问方便吐露一下咱们最后验证集合ppl 降到了多少吗？ xx

> 英文是2 epoch，中文是1 epoch
> 
> 我们用的英文数据集只有大概6B token，比较少，所以重复了两次 中文数据大概有150B token，我们只采样了一部分进行训练

**Comment by jubgjf** [comment]
英文loss大概在1.7，中文loss大概在2.6
不过不同词表的PPL可能不适合对比

**Comment by CLeafYeah** [comment]
> 英文loss大概在1.7，中文loss大概在2.6 不过不同词表的PPL可能不适合对比

感谢回复！
