### ISSUE TITLE
init_embeddings 模型转换问题

### ISSUE THREAD

**Issue by dachengai** [HIT-SCIR/Chinese-Mixtral-8x7B#14]
![image](https://github.com/HIT-SCIR/Chinese-Mixtral-8x7B/assets/8870735/28afd597-4586-4101-9ae0-c51dbd4ea6e9)

mixstral 8x7b  开源模型是 safetensors 格式， 这里要改成： 

model = AutoModelForCausalLM.from_pretrained(old_model, device_map="auto", torch_dtype=torch.bfloat16,trust_remote_code=True)
model_dict = model.state_dict()

**Comment by jubgjf** [comment]
感谢您的提醒，我们会更新这部分代码
