### ISSUE TITLE
能否说下硬件需求。

### ISSUE THREAD

**Issue by orderer0001** [HIT-SCIR/Chinese-Mixtral-8x7B#16]
4090 24g可以本地加载推理吗？微调又需要多少内存呢？Qlora训练又需要多少内存呢？全量训练的内存需求很大 对吗

**Comment by jubgjf** [comment]
- 使用llama.cpp的gguf q2_k格式，可以实现18GB显存推理
  - 但是由于Chinese-Mixtral-8x7B是base模型，不建议直接加载推理本模型，而是应该进行微调再进行推理
  - 推荐我们基于Chinese-Mixtral-8x7B微调后的模型：[huozi3](https://github.com/HIT-SCIR/huozi)。我们在这个仓库中提供了量化好的gguf q2_k格式的模型检查点以及[详细的使用说明](https://github.com/HIT-SCIR/huozi#%E9%87%8F%E5%8C%96%E6%8E%A8%E7%90%86)
- 我们没有进行全参数微调，不过简单估计需要560GB显存。并且我们还没有测试ZeRO-3 + Offload是否能跑通全参数微调，建议使用[MegaBlocks](https://github.com/mistralai/megablocks-public)，训练时采用张量并行
- QLoRA训练 + 序列长度32768，需要至少80GB显存，这个时候batch size = 1能稳定训练，batch size = 2有几率在中途OOM。不过如果序列长度改小一点，batch size就可以开更大

**Comment by orderer0001** [comment]
感谢指点。那是否支持mps（mac M3芯片）？

**Comment by jubgjf** [comment]
我们还没有进行过测试，不过llama.cpp是支持Apple silicon的，所以大概率可以使用llama.cpp进行推理
