### ISSUE TITLE
请问下MMLU评测的时候有增加什么prompt吗？

### ISSUE THREAD

**Issue by matrixssy** [HIT-SCIR/Chinese-Mixtral-8x7B#17]
我自己验证原始Mixtral 8x7B非指令版本的时候，在MMLU数据集上只有62分，跟论文的70分还有你们的结果69分差距有点大，想看看是不是推理的时候有什么差异？

**Comment by matrixssy** [comment]
https://flageval.baai.ac.cn/#/trending
这个榜单里似乎是63分

**Comment by jubgjf** [comment]
在我们的README里：

> 由于不同版本的评测脚本实现细节有细微差异，为了保证评测结果的一致性和公平性，我们的评测脚本统一使用EleutherAI发布的lm-evaluation-harness，commit hash为[28ec7fa](https://github.com/EleutherAI/lm-evaluation-harness/tree/28ec7fa950346b5a895e85e1f3edd5648168acc4)。

可以用这个测一下看看

**Comment by matrixssy** [comment]
> 在我们的README里：
> 
> > 由于不同版本的评测脚本实现细节有细微差异，为了保证评测结果的一致性和公平性，我们的评测脚本统一使用EleutherAI发布的lm-evaluation-harness，commit hash为[28ec7fa](https://github.com/EleutherAI/lm-evaluation-harness/tree/28ec7fa950346b5a895e85e1f3edd5648168acc4)。
> 
> 可以用这个测一下看看

好的，感谢
