### ISSUE TITLE
没有tokenizer文件

### ISSUE THREAD

**Issue by cometyang** [HIT-SCIR/Chinese-Mixtral-8x7B#19]
哪里可以找到 tokenizer/Mixtral-8x7B-v0.1-vocab？ 在preprocessing时候无法继续

**Comment by jubgjf** [comment]
这只是一个示例路径，具体应该是：用sentencepiece训练后保存的tokenizer的路径

**Comment by cometyang** [comment]
能提供一个已经训练的tokenizer？ 或者能够提供一个比较详细的训练说明，谢谢。
是使用的这个repo提到的方法吗？https://github.com/bozheng-hit/VoCapXLM

**Comment by jubgjf** [comment]
是的

如果希望直接用训练好的，可以用我们随模型一起发布的tokenizer。可以在[这里](https://huggingface.co/HIT-SCIR/Chinese-Mixtral-8x7B/tree/main)单独下载
