### ISSUE TITLE
希望能量化成q4或者q6的形式，并尽快引入Ollama，这样个人也能用了，感谢！

### ISSUE THREAD

**Issue by ricksuzade-maker** [HIT-SCIR/Chinese-Mixtral-8x7B#2]
目前个人用户购买苹果机来运行大模型，比较可取

**Comment by AmintaCCCP** [comment]
+1 希望有gguf的

**Comment by jubgjf** [comment]
llama.cpp现在[已经支持mixtral架构](https://github.com/ggerganov/llama.cpp/pull/4406)，并且提供了hf->gguf格式转换的[教程](https://github.com/ggerganov/llama.cpp/discussions/2948)。chinese-mixtral-8x7b和原版mixtral-8x7b在架构方面没有区别，所以应该可以直接使用

**Comment by jubgjf** [comment]
我们已发布基于Chinese-Mixtral-8x7B的chat模型：[活字3.0](https://github.com/HIT-SCIR/huozi)，支持llama.cpp，AutoAWQ等量化框架，可以尝试使用
