### ISSUE TITLE
ALP横坐标意义

### ISSUE THREAD

**Issue by Jianwei-Lv** [HIT-SCIR/Chinese-Mixtral-8x7B#20]
想请问下，ALP折线图的横坐标代表的是词表大小还是语料的token数目？

**Comment by jubgjf** [comment]
横坐标是词表大小

可以参考我们的说明：
> 我们使用sentencepiece在12G知乎数据和2G悟道数据上训练中文BPE词表。我们在训练词表时分别枚举了中文单字Token数量以及***中文总Token数量***，并对二者进行组合，得到了数百个大小、内容各异的词表。为了得到最适合的词表，我们通过Zheng Bo等人提出的[ALP](https://arxiv.org/pdf/2109.07306.pdf)计算这些词表的中文词汇能力。ALP通过计算特定语言的子词切分粒度，并对词表的中低频子词进行惩罚，是一种方便快捷的衡量特定语言词汇能力的指标。
