### ISSUE TITLE
通信量不一致

### ISSUE THREAD

**Issue by longzhang418** [HIT-SCIR/Chinese-Mixtral-8x7B#21]
多卡直接用huggingface transformers的trainer，训练mixtral，遇见这种错误，请问您们有遇到过吗？
![issue](https://github.com/HIT-SCIR/Chinese-Mixtral-8x7B/assets/127946588/326239fc-45ca-480b-ab59-1ba533552570)
看起来像是，因为moe的专家路由，导致每张卡的通信量不一致了？

**Comment by jubgjf** [comment]
可能是机器的问题，我们没有遇到类似的情况。或许可以尝试设置一些NCCL的环境变量来调试
