### ISSUE TITLE
关于embedding扩展的细节

### ISSUE THREAD

**Issue by cometyang** [HIT-SCIR/Chinese-Mixtral-8x7B#22]
“在获得新词表后，我们需要对embedding和lm_head层进行扩充和初始化。我们使用新Token在旧embedding层中的词嵌入平均值对扩充部分进行初始化。在我们的前期实验中，这种方法略优于HuggingFace的默认实现，即使用固定的正态分布进行初始化。”

请问具体如何实现，可以指出具体代码位置吗？

**Comment by jubgjf** [comment]
- embedding初始化：见`models/init_embeddings.py`
- 前期实验：这部分我们是用Megatron-LM训练LLaMA2-扩词表实现的，这部分我们暂未开源。不过直接通过修改我们已开源的代码来进行试验
