### ISSUE TITLE
torchrun: command not found

### ISSUE THREAD

**Issue by lfxuan** [HIT-SCIR/Chinese-Mixtral-8x7B#23]
pytorch环境：
原始torch版本1_cu117
torch                     2.0.1
torchaudio                2.0.2
torchvision               0.15.2
更换torch版本2
torch                     2.0.1+cu118
torchaudio                2.0.2+cu118
torchvision               0.15.2+cu118

更换torch版本3
torch                     2.1.0+cu121
torchaudio                2.1.0+cu121
torchvision               0.16.0+cu121
训练容器中系统
Ubuntu22.04LTS
CUDA12.0
服务器中系统
Ubuntu22.04LTS
CUDA12.0/11.8互相切换匹配尝试

上述所有环境都尝试运行scripts/train-pt.sh，都出现“torchrun: command not found”问题，请问可能是什么原因导致？如何解决？

**Comment by jubgjf** [comment]
`torchrun`是pytorch自带的命令，请您检查是否正确安装了`torch`，以及训练启动时是否正确激活了虚拟环境。

如果还是出现找不到命令的问题，可以尝试用`python -m torch.distributed.run`代替。（参考[此讨论](https://discuss.pytorch.org/t/how-to-install-torchrun/135138)）
