### ISSUE TITLE
微调

### ISSUE THREAD

**Issue by cripsgreen** [HIT-SCIR/Chinese-Mixtral-8x7B#27]
请教一下，怎样用命令行torchrun训练微调？

**Comment by jubgjf** [comment]
首先参考`scripts/train-sft.sh`拼接出完整的torchrun命令，将所有以`SLURM`开头的变量修改为您试验中的实际值：
- `$SLURM_JOB_ID`：标识id，修改为一个唯一的实验名称
- `$SLURM_NODEID`：机器序号
  - 如果只有一台机器，设置为0或直接删除此参数即可
  - 如果有多台机器，需要设置为当前机器的序号，从0开始递增
- `$SLURM_JOB_NUM_NODES`：机器总数

然后修改`MASTER_ADDR`为主节点ip地址或hostname（能够寻址即可）

最后运行torchrun：
- 如果只有一台机器，直接运行torchrun命令
- 如果有多台机器，需要在每台机器上分别运行一次torchrun，注意参数中的`--node_rank`需要为机器序号
