### ISSUE TITLE
增量预训练出错

### ISSUE THREAD

**Issue by lwj2001** [HIT-SCIR/Chinese-Mixtral-8x7B#28]
我在使用以下命令构建了虚拟环境：
pip install torch==2.0.1 torchvision==0.15.2 torchaudio==2.0.2 --index-url https://download.pytorch.org/whl/cu117
pip install deepspeed
pip install transformers==4.36.2 datasets evaluate peft accelerate gradio optimum sentencepiece trl
pip install jupyterlab scikit-learn pandas matplotlib tensorboard nltk rouge bitsandbytes fire
pip install flash-attn --no-build-isolation
bash scripts/train-pt.sh

报错信息如下：
Traceback (most recent call last):
  File "/Data1/home/fanziqi/Project/Chinese-Mixtral-8x7B/train.py", line 227, in <module>
    train()
  File "/Data1/home/fanziqi/Project/Chinese-Mixtral-8x7B/train.py", line 204, in train
    model.print_trainable_parameters()
  File "/Data1/home/fanziqi/.conda/envs/huozi_ft/lib/python3.10/site-packages/peft/peft_model.py", line 531, in print_trainable_parameters
    trainable_params, all_param = self.get_nb_trainable_parameters()
  File "/Data1/home/fanziqi/.conda/envs/huozi_ft/lib/python3.10/site-packages/peft/peft_model.py", line 511, in get_nb_trainable_parameters
    num_bytes = param.quant_storage.itemsize if hasattr(param, "quant_storage") else 1
AttributeError: 'torch.dtype' object has no attribute 'itemsize'

我的scripts/train-pt.sh脚本内容如下：

TRAIN_DATASETS=(
    # 1:SkyPile-150B-2022
    # 0.1:SkyPile-150B-2023
    1:DKYoon-SlimPajama-6B
)

VALID_DATASETS=(
    # SkyPile-150B-2022
    # SkyPile-150B-2023
    DKYoon-SlimPajama-6B
)

TRAIN_PARAMS=""
TRAIN_PARAMS+=" --enable_lora"
TRAIN_PARAMS+=" --lora_alpha 128"
TRAIN_PARAMS+=" --lora_dropout 0.05"
TRAIN_PARAMS+=" --lora_rank 64"
TRAIN_PARAMS+=" --lora_target_modules q_proj v_proj k_proj o_proj w1 w2 w3"
TRAIN_PARAMS+=" --lora_modules_to_save embed_tokens lm_head"
TRAIN_PARAMS+=" --model_name_or_path /Data1/home/fanziqi/.cache/huggingface/modelscope/HIT-SCIR/huozi3"
TRAIN_PARAMS+=" --tokenizer_name_or_path /Data1/home/fanziqi/.cache/huggingface/modelscope/HIT-SCIR/huozi3"
TRAIN_PARAMS+=" --train_datasets ${TRAIN_DATASETS[*]}"
TRAIN_PARAMS+=" --valid_datasets ${VALID_DATASETS[*]}"
TRAIN_PARAMS+=" --dataloader_drop_last"
TRAIN_PARAMS+=" --cache_dir hf-cache"
TRAIN_PARAMS+=" --output_dir outputs/$SLURM_JOB_ID"
TRAIN_PARAMS+=" --num_train_epochs 1"
TRAIN_PARAMS+=" --model_max_length 2048"
TRAIN_PARAMS+=" --per_device_train_batch_size 4"
TRAIN_PARAMS+=" --gradient_accumulation_steps 1"
TRAIN_PARAMS+=" --optim adamw_torch_fused"
TRAIN_PARAMS+=" --per_device_eval_batch_size 4"
TRAIN_PARAMS+=" --evaluation_strategy steps"
TRAIN_PARAMS+=" --eval_steps 500"
TRAIN_PARAMS+=" --save_strategy steps"
TRAIN_PARAMS+=" --save_steps 1000"
TRAIN_PARAMS+=" --learning_rate 1e-5"
TRAIN_PARAMS+=" --warmup_ratio 0.05"
TRAIN_PARAMS+=" --logging_dir logs/tb/$SLURM_JOB_ID"
TRAIN_PARAMS+=" --logging_strategy steps"
TRAIN_PARAMS+=" --logging_steps 1"
TRAIN_PARAMS+=" --lr_scheduler_type cosine"
TRAIN_PARAMS+=" --report_to tensorboard"
TRAIN_PARAMS+=" --gradient_checkpointing"
TRAIN_PARAMS+=" --bf16"
TRAIN_PARAMS+=" --deepspeed ds-config/config.json"

TORCHRUN_PARAMS='--nproc_per_node 2  --nnodes 1 --rdzv_id=0 '

CUDA_VISIBLE_DEVICES=6,7 torchrun --master_port 29501 $TORCHRUN_PARAMS train.py $TRAIN_PARAMS

**Comment by jubgjf** [comment]
可以参考这里：https://stackoverflow.com/questions/78211526/pytorch-attributeerror-torch-dtype-object-has-no-attribute-itemsize 检查一下torch版本

**Comment by lwj2001** [comment]
还是没能解决，torch版本就是您推荐的2.0.1 + cu117，我是直接通过以下命令安装的torch：
pip install torch==2.0.1 torchvision==0.15.2 torchaudio==2.0.2 --index-url https://download.pytorch.org/whl/cu117
其他的环境依赖和您的一致

**Comment by jubgjf** [comment]
试试不加`--index-url`呢，我安装的时候没加

**Comment by lwj2001** [comment]
很抱歉，还是相同的错误
我的安装环境脚本如下：
pip install torch==2.0.1 torchvision==0.15.2 torchaudio==2.0.2
pip install transformers==4.36.2 datasets evaluate peft accelerate gradio optimum sentencepiece trl
pip install jupyterlab scikit-learn pandas matplotlib tensorboard nltk rouge bitsandbytes fire
pip3 install deepspeed
pip install flash-attn --no-build-isolation
因为环境中cuda11.7的toolkit，并且.bashrc文件已经明确指向了cuda11.7
您可以复现一下吗

**Comment by jubgjf** [comment]
要不试试升级torch版本吧，我们的代码对torch的版本要求没那么严格

**Comment by dkasa** [comment]
问题解决了吗？ 能提供下 requirements.txt 吗？或者你们在哪里查到的？

**Comment by lwj2001** [comment]
是的，问题已经解决了。
[requirements.txt](https://github.com/HIT-SCIR/Chinese-Mixtral-8x7B/files/15090131/requirements.txt)

**Comment by dkasa** [comment]
收到，感谢，我来对比下。
