### ISSUE TITLE
关于词表扩充

### ISSUE THREAD

**Issue by CrazyBoyM** [HIT-SCIR/Chinese-Mixtral-8x7B#29]
您好，想要请教一下两个问题，  
1.在词表扩充这里我们的新表是前32k个token与llama2原生一样的，只扩充后面新增的 token么，是怎么得到这样一个词表的， 在训练划分词表时可以配置一部分原先的token关系不变，还是完全训练一张新表，然后对照原始llama2的表对前32k个token重新排列一致了。  
2.在原始32k词表中可能包含1~2k个少量中文常见字，我们后面扩充的几十k 中文新增token，可能已经包含了这部分，是需要对他们从前面32k中移除掉，还是直接不用管？  
如能赐教，不胜感激 ～

**Comment by jubgjf** [comment]
1. 前32K的token与Mistral原生一致，扩充部分是直接使用sentencepiece在额外的语料上训练得到的BPE词表，细节可以参考[这里](https://github.com/HIT-SCIR/Chinese-Mixtral-8x7B#%E8%AF%8D%E8%A1%A8%E6%89%A9%E5%85%85)。在训练之后，需要对两个词表进行合并
2. 合并词表时，需要进行去重

**Comment by CrazyBoyM** [comment]
非常感谢您！！
