### ISSUE TITLE
您好，请问指令微调需要多少显存，有没有可以推荐的指令微调数据集？

### ISSUE THREAD

**Issue by tommy3266** [HIT-SCIR/Chinese-Mixtral-8x7B#3]
您好，请问指令微调需要多少显存，有没有可以推荐的指令微调数据集？

**Comment by jubgjf** [comment]
目前发布的版本没有进行指令微调，但是最小显存需求应该和预训练差不多：#1 

指令微调的数据可以参考HuggingFace的[blog](https://huggingface.co/blog/mixtral#fine-tuning-with-%F0%9F%A4%97-trl)以及[wangrongsheng/Aurora](https://huggingface.co/wangrongsheng/Aurora)
