### ISSUE TITLE
TypeError: SFTConfig.__init__() got an unexpected keyword argument 'cache_dir'

### ISSUE THREAD

**Issue by wormcode** [HIT-SCIR/Chinese-Mixtral-8x7B#31]
=========================================
/root/miniconda3/lib/python3.10/site-packages/huggingface_hub/utils/_deprecation.py:100: FutureWarning: Deprecated argument(s) used in '__init__': max_seq_length, neftune_noise_alpha, dataset_text_field. Will not be supported from version '1.0.0'.

Deprecated positional argument(s) used in SFTTrainer, please use the SFTConfig to set these arguments instead.
  warnings.warn(message, FutureWarning)
Traceback (most recent call last):
  File "/root/AD/Chinese-Mixtral-8x7B/train.py", line 346, in <module>
    train()
  File "/root/AD/Chinese-Mixtral-8x7B/train.py", line 329, in train
    trainer = partial_trainer(
  File "/root/miniconda3/lib/python3.10/site-packages/huggingface_hub/utils/_deprecation.py", line 101, in inner_f
    return f(*args, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/trl/trainer/sft_trainer.py", line 152, in __init__
    args = SFTConfig(**args_as_dict)
TypeError: SFTConfig.__init__() got an unexpected keyword argument 'cache_dir'

以下内容便于 调查
1.  train.py

@dataclass
class TrainingArguments(transformers.TrainingArguments):
cache_dir: Optional[str] = field(default=None)

2.  .../lib/python3.10/site-packages/trl/trainer/sft_config.py

3.  ..../lib/python3.10/site-packages/trl/trainer/sft_trainer.py

elif args is not None and args.__class__.__name__ == "TrainingArguments":
            args_as_dict = args.to_dict()
            # Manually copy token values as TrainingArguments.to_dict() redacts them
            args_as_dict.update({k: getattr(args, k) for k in args_as_dict.keys() if k.endswith("_token")})
            args = SFTConfig(**args_as_dict)

个人建议： 取消所有 cache_dir parameters in train.py
用类似  os.environ['HF_HOME'] = '/root/xx/cache/'   全局变量  或者设置为 环境变量 代替， hf 代码似乎有专门处理的地方。

另外是否说明，这个代码没有经过 SFT的训练？

**Comment by jubgjf** [comment]
感谢您的反馈，这个问题可能是由于huggingface系列库的更新，导致部分api发生了变动。
您目前可以尝试会退transformers、accelerate等库的版本来运行我们的代码。我们会在未来更新代码以适配新版依赖库。
