### ISSUE TITLE
词表扩充数据：12G知乎数据和2G悟道数据上训练中文BPE词表

### ISSUE THREAD

**Issue by LiuChaoXD** [HIT-SCIR/Chinese-Mixtral-8x7B#5]
你好，

我看到你们使用的是“12G知乎数据和2G悟道数据上训练中文BPE词表“

我的问题有两个：
1. 选择这两个数据集是你们的经验吗？即这两个数据集的中文质量高。对吧？
2. 这两个数据集从哪里下载呢？

感谢你们的这个repo，我也学习了很多。

**Comment by jubgjf** [comment]
知乎数据是我们爬取的，悟道数据是[智源开源的数据](https://github.com/BAAI-WuDao/Data)。这两部分质量都比较高

**Comment by LiuChaoXD** [comment]
> 知乎数据是我们爬取的，悟道数据是[智源开源的数据](https://github.com/BAAI-WuDao/Data)。这两部分质量都比较高

多谢你的回答。
