### ISSUE TITLE
4bit量化推理速度变慢

### ISSUE THREAD

**Issue by snowlixue** [HIT-SCIR/Chinese-Mixtral-8x7B#6]
您好。在A800上用4bit加载模型推理速度反而比不量化更慢了，几乎慢了一倍。请问是什么原因呢

**Comment by jubgjf** [comment]
QLoRA中，模型权重不可在4bit精度计算，必须反量化为bf16再计算，所以整体速度会变慢

可以参考[HuggingFace的博客](https://huggingface.co/blog/zh/4bit-transformers-bitsandbytes#qlora%EF%BC%8C%E7%BB%8F%E7%94%B1%E9%87%8F%E5%8C%96%E5%AE%9E%E7%8E%B0%E5%A4%A7%E6%A8%A1%E5%9E%8B%E8%87%AA%E7%94%B1%E7%9A%84%E6%96%B0%E9%80%94%E5%BE%84)以及[Google Cloud文档](https://cloud.google.com/vertex-ai/docs/model-garden/lora-qlora?hl=zh-cn)，提到了QLoRA的计算方式和速度问题

**Comment by snowlixue** [comment]
我用的是88G的Chinese-Mixtral-8x7B模型，所以这里面也有QLoRA的权重吗

**Comment by jubgjf** [comment]
88G的Chinese-Mixtral-8x7B模型是【LoRA权重】 + 【原Mixtral-8x7B权重】合并后的模型，精度是bf16，不是单独的QLoRA权重

使用4bit进行加载，就会导致产生额外计算量用于反量化

**Comment by snowlixue** [comment]
了解了，非常感谢
